Refactored to specific corpus as flag or environment variable for association rule scripts.

diff --git a/src/confidence b/src/confidence
--- a/src/confidence
+++ b/src/confidence
@@ -6,14 +6,20 @@ NAME
   ${me} - Confidence in an association rule.
 
 SYNOPSIS
-  ${me} [OPTIONS] antecedent consequent directory
+  ${me} [OPTIONS] antecedent consequent
 
 DESCRIPTION
   ${me} returns the confidence of an association between the antiecedent
-        and the consequent over a directory of set files.
+        and the consequent.
 
 OPTIONS
   -h  Displays help message.
+
+  -d corpus
+    Specifies the directory with the data base of transaction itemsets.
+    Defaults to current directory or the CORPUS environment variable,
+    if set.
+
 
 AUTHOR
   Implementation by Berend M. Tober.
@@ -33,15 +39,17 @@ checkscript "support"
 checkscript "union"
 checkscript "dc"
 
-
-directory="./"
-
 while [[ $# -gt 0 ]]
 do
   case "${1}" in
     -h)
       echo "${usage}"
       exit
+      ;;
+    -d)
+      shift
+      CORPUS="${1}"
+      [ ! -d "${CORPUS}" ] && echo "${CORPUS} is not a directory or not found." && exit 1
       ;;
     -*)
       echo "Invalid option '${1}'"
@@ -50,22 +58,19 @@ do
     *)
       antecedent="${1}"
       consequent="${2}"
-      directory="${3-./}"
-      shift 3
+      shift 2
       ;;
   esac
   shift
 done  
 
+
 [ ! -f  "${antecedent}" ] && echo "Antecedent '${antecedent}' not found." && exit
 [ ! -f  "${consequent}" ] && echo "Consequent '${consequent}' not found." && exit
+: ${CORPUS?}
 
-tmpfile=".$(basename $0).$$"
-trap 'rm "${tmpfile}"' EXIT
-union "${antecedent}" "${consequent}" > "${tmpfile}"
-
-numerator=$(support "${tmpfile}" "${directory}")
-denominator=$(support "${antecedent}" "${directory}")
+numerator=$(support "${antecedent}" "${consequent}")
+denominator=$(support "${antecedent}")
 
 dc <<< "10k$numerator $denominator /p"
 
diff --git a/src/lift b/src/lift
--- a/src/lift
+++ b/src/lift
@@ -6,14 +6,19 @@ NAME
   ${me} - Lift of an association rule.
 
 SYNOPSIS
-  ${me} [OPTIONS] antecedent consequent directory
+  ${me} [OPTIONS] antecedent consequent
 
 DESCRIPTION
   ${me} returns the lift an association between the antiecedent
-        and the consequent over a directory of set files.
+        and the consequent.
 
 OPTIONS
   -h  Displays help message.
+
+  -d corpus
+    Specifies the directory with the data base of transaction itemsets.
+    Defaults to current directory or the CORPUS environment variable,
+    if set.
 
 AUTHOR
   Implementation by Berend M. Tober.
@@ -42,6 +47,11 @@ do
       echo "${usage}"
       exit
       ;;
+    -d)
+      shift
+      CORPUS="${1}"
+      [ ! -d "${CORPUS}" ] && echo "${CORPUS} is not a directory or not found." && exit 1
+      ;;
     -*)
       echo "Invalid option '${1}'"
       exit
@@ -63,9 +73,9 @@ tmpfile=".$(basename $0).$$"
 trap 'rm "${tmpfile}"' EXIT
 union "${antecedent}" "${consequent}" > "${tmpfile}"
 
-numerator=$(support "${tmpfile}" "${directory}")
-denominatorX=$(support "${antecedent}" "${directory}")
-denominatorY=$(support "${consequent}" "${directory}")
+numerator=$(support "${tmpfile}")
+denominatorX=$(support "${antecedent}")
+denominatorY=$(support "${consequent}")
 
 dc <<< "10k$numerator $denominatorX $denominatorY */p"
 
diff --git a/src/support b/src/support
--- a/src/support
+++ b/src/support
@@ -6,15 +6,24 @@ NAME
   ${me} - Support of an item set.
 
 SYNOPSIS
-  ${me} [OPTIONS] itemset directory
+  ${me} [OPTIONS] itemset
+  ${me} [OPTIONS] antecedent consequent
 
 DESCRIPTION
-  ${me} returns the support of an itemset amongst transactions in directory. 
+  The first form returns the support of an itemset.  The second form
+  returns the support of a implication for antecedent to consequent
+  item sets.
 
 OPTIONS
   -h  Displays help message.
 
   -l  List the set files that match the item set.
+
+  -d corpus
+    Specifies the directory with the data base of transaction itemsets.
+    Defaults to current directory or the CORPUS environment variable,
+    if set.
+
 
 AUTHOR
   Implementation by Berend M. Tober.
@@ -32,11 +41,12 @@ checkscript ()
 }
 
 checkscript "includes"
+checkscript "members"
 checkscript "dc"
 
-itemset="-"
-directory="./"
 unset listmatches
+itemset=".${me}.$$"
+trap 'rm "${itemset}"' EXIT
 
 while [[ $# -gt 0 ]]
 do
@@ -48,24 +58,29 @@ do
     -l)
       listmatches="true"
       ;;
+    -d)
+      shift
+      CORPUS="${1}"
+      [ ! -d "${CORPUS}" ] && echo "${CORPUS} is not a directory or not found." && exit 1
+      ;;
     -*)
       echo "Invalid option '${1}'"
       exit
       ;;
     *)
-      itemset="${1--}"
-      directory="${2-./}"
-      shift 2
+      members "${1--}" >> "${itemset}"
       ;;
   esac
   shift
 done  
 
+: ${CORPUS?}
+
 [ ! -f  "${itemset}" ] && echo "Itemset '${itemset}' not found." && exit
 
 numerator=0
 denominator=0
-for n in $(find "${directory}" -type f)
+for n in $(find "${CORPUS}" -type f)
 do
   denominator=$((denominator + 1))
   includes "${itemset}" "${n}"
